name: Substitue variable
description: Substitute variables for JSON/XML - first release will support JSON
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}  
  type:
    required: true
    default: ''
  prefix:
    required: true
    default: ''
  files:
    required: true
    default: ''
  prerelease:
    required: true
    default: no
  body:
    required: true
    default: ''
  create-release:
    required: true
    default: 'yes'
  branch:
    required: false
    default: ${{ github.event.repository.default_branch }}
  
  
outputs:
  version:
    description: version
runs:
  using: "node16"
  main: src/index.js